### ISSUE TITLE
Пропал звук в голосовых сообщениях и видео

### ISSUE THREAD

**Issue by ogustbiller** [blacksailer/depecher#123]
## Description

После обновления системы до 3.0.3.9  пропал пропал звук при воспроизведении голосовых сообщений и видео.
## Environment

* Depecher version: v 0.6.0
* SailfishOS version: 3.0.3.9
* SailfishOS device: Sony Xperia X Compact 

## Steps to reproduce

1. Отправил аудио сообщение, например, себе.
2. Воспроизвожу
3. Тишина.

**Comment by frzifus** [comment]
w00t?

**Comment by ogustbiller** [comment]
Вылечилось перезагрузкой.

**Comment by frzifus** [comment]
wjfdlksjfsldkjfaklsjdösdjkals???

**Comment by raketti** [comment]
Topic: The sound in voice messages and video was gone
Description: After updating the system to 3.0.3.9, the sound disappeared when playing voice messages and video.
Steps:
1. I sent a video message, for example, to myself.
2. Reproduce
3. Silence

Apologies on the crude translation it was provided by Google. :)

**Comment by ogustbiller** [comment]
> Topic: The sound in voice messages and video was gone
> Description: After updating the system to 3.0.3.9, the sound disappeared when playing voice messages and video.
> Steps:
> 
> 1. I sent a video message, for example, to myself.
> 2. Reproduce
> 3. Silence
> 
> Apologies on the crude translation it was provided by Google. :)

Quite correct. Thank you.


This bug go out after phone reboot.
