### ISSUE TITLE
got banned!

### ISSUE THREAD

**Issue by alireza1219** [blacksailer/depecher#125]
Hi!
after using depecher for a while, my whole account got banned and it's not useable anymore
I never faced something like this before
Is telegram trying to do something with the depecher libraries? like banning them?

**Comment by alireza1219** [comment]
![Screen Shot 2019-05-27 at 11 57 51 AM](https://user-images.githubusercontent.com/46503882/58403011-e0f29000-8076-11e9-9273-df092fc0950a.png)

**Comment by blacksailer** [comment]
Hello! I've never encountered something like this. Maybe you should contact Telegram for reasons?

**Comment by alireza1219** [comment]
> Hello! I've never encountered something like this. Maybe you should contact Telegram for reasons? Can you tell how long and when you started to use depecher? and what version did you use

Hi :) 
Already contacted telegram team, waiting for any respond from them
Well, I'm using it from the beginning, ( back to 2018 ) that's why I said I never see something like this before
it was the last version ( also tdlibjson were at the last version )
After that accident also tried making new accounts with my other phone numbers and unfortunately same thing happened again ( Within a minutes, Throws me out from any telegram client I'm using with those numbers and once I try to log in again, I'll face with the "Banned number" error )

**Comment by alireza1219** [comment]
12 hours later and now I'm unbanned
It's very odd! still no responds from Telegram support team

**Comment by blacksailer** [comment]
Is there an explanation?

**Comment by alireza1219** [comment]
Oh sorry I almost forgot, yes but doesn't help much about what is wrong or where the problem came from :
![Screen Shot 2019-05-30 at 7 24 26 PM](https://user-images.githubusercontent.com/46503882/58641579-b58ad200-8310-11e9-8b5d-0e2ed6fb6d78.png)

**Comment by frzifus** [comment]
It would have surprised me. depecher uses the official tdlib json from telegram. :yin_yang:

**Comment by blacksailer** [comment]
you do not know how much it suprised me =)
