### ISSUE TITLE
Change location of `depecherDatabase` folder

### ISSUE THREAD

**Issue by GoAlexander** [blacksailer/depecher#14]
I think that it is better to change location of `depecherDatabase` folder from ~ to `~/.local/share/harbour-depecher`.

**Comment by paolomi** [comment]
Furthermore, I propose to make the package more "harbour compliant". I mean:
rename depecher.rpm to harbour-depecher.rpm
rename /usr/bin/depecher  to  /usr/bin/harbour-depecher
rename /usr/share/depecher  to /usr/share/harbour-depecher
rename /usr/share/applications/depecher.desktop  to /usr/share/applications/harbour-depecher.desktop
rename /usr/share/icons/hicolor/*/apps/depecher.png to /usr/share/icons/hicolor/*/apps/harbour-depecher.png
That's all.

**Comment by blacksailer** [comment]
Moving data lo .local is good opinion. But why making harbour-compliant? I'm not planning to post to jolla harbour. depecher will not pass harbour verification

**Comment by GoAlexander** [comment]
@blacksailer You can`t use tdlib library in Harbour?

**Comment by paolomi** [comment]
well, if you plan to never post it on jolla store, then ignore my request.

Changing location to .local/share is enough :+1:
