### ISSUE TITLE
Crash after sign in somewhere in AboutMeDao::setInfo

### ISSUE THREAD

**Issue by ksiazkowicz** [blacksailer/depecher#15]
Every time I try to log in, app will crash and won't open unless I remove depecherDatabase directory. According to stack trace, it happens somewhere here:
![image](https://user-images.githubusercontent.com/1162358/39093185-ba76a510-461b-11e8-8f45-9757374b2d7b.png)

I don't have an avatar picture set on my Telegram account, if that matters.

**Comment by jaykijay** [comment]
Same Issue here: 
Program received signal SIGSEGV, Segmentation fault.
0xaac82b50 in tdlibQt::AboutMeDAO::setInfo (this=0xaacfb280, meObject=...) at /usr/include/qt5/QtCore/qsharedpointer_impl.h:306
306     /usr/include/qt5/QtCore/qsharedpointer_impl.h: No such file or directory.

**Comment by blacksailer** [comment]
Should be fixed in 0.1-2 version. Please check.
