### ISSUE TITLE
[Question] Build on 64-bit Linux...

### ISSUE THREAD

**Issue by Koluchy** [blacksailer/depecher#152]
Hi!
Can you please tell me if it is possible to build the project on 64 bit Ubuntu? And if so, how?
Thanks.

**Comment by blacksailer** [comment]
Hello, you mean in SailfishOS SDK to work on it? 22 сент. 2020 г. 16:50 пользователь Koluchy <notifications@github.com> написал:
Hi!
Can you please tell me if it is possible to build the project on 64 bit Ubuntu? And if so, how?
Thanks.

**Comment by Koluchy** [comment]
I wanted to use AuroraSDK...(AuroraSDK-3.2.1.65-base-linux-64-offline-release-200724-9f2b70c64d-cca7449a8d.run) from https://sdk-repo.omprussia.ru/sdk/installers/3.2.1/
But...project require tdlibjson for i486...

**Comment by Koluchy** [comment]
Oh, sorry, just now I realized that I asked the wrong question ... Delete it, please)
