### ISSUE TITLE
Build in AuroraOS SDK 3.2.1.65 build machine

### ISSUE THREAD

**Issue by Koluchy** [blacksailer/depecher#153]
I am trying to build a project in the AuroraOS SDK build environment.
For this:
1. download project repo and the tdlibjson tdlibjson-devel packages from the rpm link in /home/user directory.
2. connected via ssh to the build machine.
3. installed downloaded packages (sudo rpm -i tdlibjson...)
4. start the build from the project directory with the command: mb2 -t AuroraOS-3.2.1.65-base-i486 -s rpm/dependent.spec build
5. Got the result:
No provider of 'pkgconfig (tdlibjson)' found.
Building target platforms: i486-meego-linux-gnu
Building for target i486-meego-linux-gnu
error: Failed build dependencies:
pkgconfig (libdbusaccess) is needed by dependent-0.7.3-1.i486
pkgconfig (nemonotifications-qt5) is needed by dependent-0.7.3-1.i486
pkgconfig (openssl) is needed by dependent-0.7.3-1.i486
pkgconfig (tdlibjson) is needed by depencher-0.7.3-1.i486
pkgconfig (vorbisfile) is needed by dependent-0.7.3-1.i486
sailfish-svg2png> = 0.1.5 is needed by depencher-0.7.3-1.i486

Wherein:
[mersdk @ SailfishSDK ~] $ rpm -q tdlibjson
tdlibjson-1.4.0-1.15.2.jolla.i486
[mersdk @ SailfishSDK ~] $ rpm -q libdbusaccess
libdbusaccess-1.0.10-1.3.7.omp.i486
[mersdk @ SailfishSDK ~] $ rpm -q openssl
openssl-1.0.2o + git4omp1-1.6.4.omp.i486
[mersdk @ SailfishSDK ~] $ pkg-config --libs --cflags tdlibjson
-I / usr / include / td -ltdjson
[mersdk @ SailfishSDK ~] $ pkg-config --libs --cflags libdbusaccess
-pthread -I / usr / include / dbusaccess -I / usr / include / gutil -I / usr / include / glib-2.0 -I / usr / lib / glib-2.0 / include -ldbusaccess
[mersdk @ SailfishSDK ~] $ pkg-config --libs --cflags openssl
-lssl -lcrypto

Can you please tell me what I am doing wrong?
Thanks.

**Comment by blacksailer** [comment]
Is devel package installed? It contains tdlibjson. pc file

**Comment by Koluchy** [comment]
[mersdk@SailfishSDK lib]$ ls pkgconfig
...tdlibjson.pc

[mersdk@SailfishSDK depecher-master]$ zypper se tdlibjson-dev
Loading repository data...
Reading installed packages...
S | Name            | Summary                                   | Type   
--+-----------------+-------------------------------------------+--------
i | tdlibjson-devel | Development files for Telegram TD library | package

[mersdk@SailfishSDK depecher-master]$ pkg-config --libs --cflags tdlibjson
-I/usr/include/td -ltdjson

**Comment by blacksailer** [comment]
I will try on Ubuntu and come back here

**Comment by Koluchy** [comment]
The issue was resolved after installing dependencies inside scratchbox. Thanks!
