### ISSUE TITLE
Segmentation fault in chat overview

### ISSUE THREAD

**Issue by Frzifus** [blacksailer/depecher#17]
When I scroll down in the chat overview the program ends because of a segmentation fault.

![segfault](https://user-images.githubusercontent.com/10403402/39096473-cf5af5dc-4650-11e8-8900-3576036b03b6.jpg)

**Comment by blacksailer** [comment]
Should be fixed in 0.1-2 version. Please check.

**Comment by Frzifus** [comment]
works flawlessly
