### ISSUE TITLE
Logging in issue

### ISSUE THREAD

**Issue by marxistvegan** [blacksailer/depecher#19]
I get the Telegram code via my other Telegram client that is logged in. When I enter the number it then shows the First Name and Last Name Fields, but the  'Sending Request' remains greyed out. However I can advance to the Depecher by gesture swipe right to left, but it does not populate with current or past messages from contacts. Nor does it receive a new message. 

I started it from command line and see on "Logic Error Caught" 

Not certain if geolocation is relevant but trying to connect from the US

**Comment by blacksailer** [comment]
Hello!
Geolocation is irrelevant.

Logic error caught - is okay, I remove it because it draws too many attention) If you see "Logic error caught" - it means that Telegram doesn't have for you any updates within 10 sec.

Yep, you encountered a bug, you should enter code and then push a button. It's the must feature that I should fix.

To sum up:
If you already have account in Telegram:
- reveive a telegram code
- enter code
- Push a button
- Swipe to right

If you doens't have a Telegram account:
- reveive a telegram code
- enter code, First name and Last name
- Push a button
- Swipe to right

**Comment by marxistvegan** [comment]
@blacksailer so is there any work around? 
Currently the application is not functional.

**Comment by jaykijay** [comment]
Are you using newest Version? (0.1-2) ? 
I had this bug with old Version but was fixed in new.

**Comment by marxistvegan** [comment]
I am using 0.1-2 and that was both by upgrading it from the previous version and also by way of removing and reinstalling it and the libraries. Still same problem

**Comment by blacksailer** [comment]
If you already registered in Telegram, then button will be enabled if you enter code in TextField.
If you do not have account in Telegram and you trying to use it in first, then you should input First name and Last name. 

In bottom is line of code that responsible for enabling button

https://github.com/blacksailer/depecher/blob/615cc4e95d5ae3e9eecaf01e43a275b23e8ebb7a/depecher/qml/pages/components/authorization/SignInDialog.qml#L91


If do everything correctly and issue is still happening please tell, can you login via web.telegram.org? If yes, please contact me @blacky_i I'll send package with logging (Sorry for such troubling resolving issue)

**Comment by marxistvegan** [comment]
Let me get back to you, I flooded attempts that the web.telegram.org does not currently work, so that might be part of the error here too. That being said maybe it would be possible to show an error in logging in as the web.telegram.org shows?

**Comment by blacksailer** [comment]
Well, your issue not investigated, but error handling is very important) I'll added as soon as possible.

**Comment by marxistvegan** [comment]
OK user error. I did not realize I had two-step authorization enabled. This can be closed unless you want to leave it open to set up a way that a message is reported in why it is not working. Sorry for the confusion completely on my part.

**Comment by blacksailer** [comment]
Fixed in version 0.2
