### ISSUE TITLE
Error in `depecher': free(): invalid pointer

### ISSUE THREAD

**Issue by paolomi** [blacksailer/depecher#2]
On my old jolla1 (sailfish os version 2.1.4.14), depecher doesn't run:

`[nemo@Sailfish ~]$ depecher 
[D] unknown:0 - Using Wayland-EGL
*** Error in `depecher': free(): invalid pointer: 0x403e3c69 ***
Aborted
`

**Comment by blacksailer** [comment]
is package tdlibjson installed?

could you run in terminal ```rpm -q tdlibjson``` ?

**Comment by paolomi** [comment]
yes, it is installed.

> [nemo@Sailfish ~]$ rpm -q tdlibjson
tdlibjson-1.2.0-1.armv7hl

>

**Comment by blacksailer** [comment]
What device and what version of Sailfish OS?


>Пятница, 20 апреля 2018, 14:33 +03:00 от paolomi <notifications@github.com>:
>
>yes, it is installed.
>>[nemo@Sailfish ~]$ rpm -q tdlibjson
>>tdlibjson-1.2.0-1.armv7hl
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С уважением, Иван Черненький

**Comment by paolomi** [comment]
it's written in the first post: the device is jolla1
https://www.gsmarena.com/jolla_jolla-5457.php
and sailfish os version is 2.1.4.14

ps: I've run gdb but there is nothing useful (no debuginfo)

> [D] unknown:0 - Using Wayland-EGL
Missing separate debuginfo for /usr/lib/libhybris/eglplatform_wayland.so
Try: zypper install -C "debuginfo(build-id)=126deac1b758ea75c744650635aa5702bb6b060b"
Missing separate debuginfo for /usr/lib/libhybris-eglplatformcommon.so.1
Try: zypper install -C "debuginfo(build-id)=df066db2701f8d7671117971742f1200ba42b7ab"
Missing separate debuginfo for /usr/lib/libwayland-server.so.0
Try: zypper install -C "debuginfo(build-id)=5870c6a10daff7c5cfa3d0702a91336a501a7640"
*** Error in `/usr/bin/depecher': free(): invalid pointer: 0x43c85c69 ***

Program received signal SIGABRT, Aborted.
0x41904bf6 in ?? () from /lib/libc.so.6

>

**Comment by blacksailer** [comment]
Try remove entirely folder ```/home/nemo/depecherDatabase``` and start app.

**Comment by paolomi** [comment]
After having removed that folder, now it works: many thanks! Now i close this bug
