### ISSUE TITLE
Add avatars in chats

### ISSUE THREAD

**Issue by GoAlexander** [blacksailer/depecher#21]
Add user avatars in chats (as in Sailorgram or in official Telegram app)

**Comment by blacksailer** [comment]
Hello!

Do you mean in group chats? Whrn viewing messages?

Вторник, 24 апреля 2018 г получено от Alexander Dydychkin:
> Add user avatars in chats
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/blacksailer/depecher/issues/2

-- 
С уважением,
Черненький Иван

**Comment by Frzifus** [comment]
the official android client displays the avatars next to each message. it doesn't matter if it is a group chat or not.

**Comment by GoAlexander** [comment]
I agree with @Frzifus 
Simple near each message in each chat (as in desktop app / android clients).

**Comment by blacksailer** [comment]
Added in version 0.2
