### ISSUE TITLE
Duplicate messages bug

### ISSUE THREAD

**Issue by savegame** [blacksailer/depecher#24]
When i use another client, in depecher all messages a duplicates, but when i close chat, and reopen it, all look fine. 
![_ _20180424_001](https://user-images.githubusercontent.com/16311332/39184378-cfbb8830-47cb-11e8-8147-47c00005e9d4.png)

**Comment by gomerust** [comment]
This affects me too, this happens in the opened chat, doesn't matter if depecher is minimized or open

**Comment by blacksailer** [comment]
Fixed in version 0.2
