### ISSUE TITLE
Too many notifications it not used for a while

### ISSUE THREAD

**Issue by Zloklun** [blacksailer/depecher#27]
When I don't use Depecher for a couple of days (and use another client instead) and start Depecher again, it loads all unread history creating a notification for every message. That's annoying.

I suggest not notifying user of old messages. Depecher can show number of unread messages, for example.

**Comment by blacksailer** [comment]
Yep, I'm currently working on that

**Comment by blacksailer** [comment]
Fixed in version 0.2
