### ISSUE TITLE
load all message instantly

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#33]
as of now we have to swipe on "load newer messages" to continue read new messages. Wouldn't be more handy to have all the messages already loaded, so we can just scroll the chat?

**Comment by blacksailer** [comment]
It's time consuming operation. In case of loder messages ```fetchMore()``` of abstract model is working, but it only works in one side of ending collection. To workaround this, pulley menu implemented. 

If there is some examples to fetchMore on both ends, will be help from community. Maybe should play on contentY property of ListView.

**Comment by DylanVanAssche** [comment]
I might figure this out when I can build it :)
This feature is already implemented in the Matrix client Matriski using the contentY property, that's what's I'm going to try to implement in Depecher.

**Comment by legacychimera247** [comment]
well it was just a suggestion...don't worry if it's too difficult...

**Comment by ksiazkowicz** [comment]
What about having an option to scroll to bottom without loading all the history, just latest messages?

**Comment by legacychimera247** [comment]
this was released too in latest update, so closing it
