### ISSUE TITLE
can't return to send photos after having selected "documents"

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#35]
the title pretty much explains everything, if i select the send button i am prompted with the grid of photos where i can choose a photo or select from various medias (at the time only photos and documents), if i select documents and then i re-select photos the photo grid is empty and i have to exit from the send menu and re-enter it again...

not a crucial thing of course, just thought about reporting it... :)

**Comment by blacksailer** [comment]
Thanks, better to write than not to write)
will fix.

**Comment by blacksailer** [comment]
Fixed in version 0.2-3
