### ISSUE TITLE
Invalid pointer on build

### ISSUE THREAD

**Issue by DylanVanAssche** [blacksailer/depecher#37]
Hi,

I'm trying to build Depecher in the SDK but I'm having some troubles...

This is my setup:

- master branch
- tdjson + tdjson-devel installed in the SDK
- latest Sailfish SDK

After building, the app directly crashed with the following error:
```
[D] unknown:0 - QML debugging is enabled. Only use this in a safe environment.
[D] main:33 - "Couldn't load translation for locale C from /usr/share/depecher/translations"
[D] unknown:0 - Using Wayland-EGL
*** Error in `/usr/bin/depecher': free(): invalid pointer: 0x40eb1c69 ***
Process killed by signal
```

I think the invalid pointer is coming from the translations?

**Comment by blacksailer** [comment]
Hello!
Is tdlibjson installed on emulator/device?

**Comment by DylanVanAssche** [comment]
Yes it's installed on the device.
Depecher in RPM form works, just not when I try to build it in the SDK. I added the APP_HASH and APP_ID too.

**Comment by blacksailer** [comment]
It's not a QTranslator, seems to me this error goes from TdlibJsonWrapper constructor. It can't build a client from tdlib.

I try on clean install sdk to recreate issue

**Comment by blacksailer** [comment]
I tried to recreate an issue, but with no success.
I've installed fresh latest sdk (1801), increased Sailfish Buld Machine RAM to 1024 Mb(TdApi.o can't be built , requires more RAM) and added repo in build machine with commands (example below shows adding repo to i486 target):
```
export KEYPATH=/path/to/SailfishSDK/vmshare/ssh/private_keys/mersdk
 ssh -i KEYPATH -p 2222 mersdk@localhost
[mersdk] -  sb2 -t SailfishOS-2.1.4.13-i486 -m sdk-install -R zypper ar -f https://sailfish.openrepos.net/BlackSailer/personal-main.repo
[mersdk] -  sb2 -t SailfishOS-2.1.4.13-i486 -m sdk-install -R rpm --import https://sailfish.openrepos.net/openrepos.key
[mersdk] -  sb2 -t SailfishOS-2.1.4.13-i486 -m sdk-install -R zypper ref
```
And after that installed in SDK's Qt Creator packages:

- tdlibjson
- tdlibjson-devel
- nemo-qml-plugin-notifications-qt5-devel

I think that it can't link to tdlibjson for some reason. That error may go from here - https://github.com/blacksailer/depecher/blob/06d1a2d94b916de86061fe21e414948a4c7ea0ce/tdlibjson_wrapper/tdlibQt/TdlibJsonWrapper.cpp#L13
Could you try to run on emulator? (To be noted, in emulator repo must be added too or install tdlibjson.rpm manually)

**Comment by DylanVanAssche** [comment]
I will try it this weekend, I was/am very busy this week :)

**Comment by DylanVanAssche** [comment]
Hi :)

I tried it in the emulator, the emulator version doesn't crash but fails to detect that the account isn't logged in. You get an empty page with Depecher as title but no contacts/groups.

Output:
```

[D] unknown:0 - QML debugging is enabled. Only use this in a safe environment.
[D] main:33 - "Couldn't load translation for locale en_US from /usr/share/depecher/translations"
[D] unknown:0 - Using Wayland-EGL

[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"updateAuthorizationState\",\"authorization_state\":{\"@type\":\"authorizationStateWaitTdlibParameters\"}}"
[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"error\",\"code\":401,\"message\":\"Initialization parameters are needed\",\"@extra\":null}"
[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"error\",\"code\":401,\"message\":\"Initialization parameters are needed\",\"@extra\":\"getMe\"}"
[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"error\",\"code\":401,\"message\":\"Initialization parameters are needed\",\"@extra\":null}"
[D] tdlibQt::ListenObject::listen:53 - Logic error caught
[D] tdlibQt::ListenObject::listen:53 - Logic error caught
[D] tdlibQt::ListenObject::listen:53 - Logic error caught
[D] tdlibQt::ListenObject::listen:53 - Logic error caught
[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"error\",\"code\":401,\"message\":\"Initialization parameters are needed\",\"@extra\":\"getMe\"}"
[D] tdlibQt::ParseObject::parseResponse:25 - "{\"@type\":\"error\",\"code\":401,\"message\":\"Initialization parameters are needed\",\"@extra\":null}"

```

**Comment by blacksailer** [comment]
seems to me it lacks appid and apphash. Look the tdlibparameters qstring in tdlibjsonwrapper at line 15. tdlib can't get correct parameters. something missing

**Comment by DylanVanAssche** [comment]
My `api_secret.pri` in the tdlibjsonwrapper folder contains the following:

```
app_id = XXXX
app_hash = abcdefghijklm
```

**Comment by DylanVanAssche** [comment]
I rechecked my Telegram API hash and ID, they are correct.
However, in the Depecher you use APPID and APP_HASH, not app_id and app_hash as described in the build docs. I checked the parameters and they are empty:

```json
{
\"@type\":\"setTdlibParameters\",
\"parameters\":{
    \"database_directory\":\".local/share/harbour-depecher\",
    \"api_id\":,
    \"api_hash\":\"\",
    \"system_language_code\":\"English\",
    \"device_model\":\"SailfishOS 2.1.4.13 (Lapuanjoki)\",
    \"system_version\":\"2.1.4.13\",
    \"application_version\":\"0.2\",
    \"use_message_database\":true,
    \"use_secret_chats\":false,
   \"enable_storage_optimizer\":true
   }
}
```

**Comment by blacksailer** [comment]
That's odd. After run qmake, in tdlibson_wrapper/tdlibQt/include/AppApiInfo.hpp should be generated with yours appid and apphash. (I use upper register for macro variable). 

Let's check that qmake substitution works. (If so, app should be run successfully).
Assume that app_id = 12345678 and app_hash = QWEASD123ASD.
First, we should change tdlibjson_wrapper.pro to look like [this](https://gist.github.com/blacksailer/9c0c068026927cee63885416bb2e54dc)

After that, in Qt Creator right click on tdlibjson_wrapper project and choose "run qmake".

At the end  we go to path /path/to/depecher_project/tdlibson_wrapper/tdlibQt/include and should find AppApiInfo.hpp that  must look like [this](https://gist.github.com/blacksailer/d14eacdd5cf185140a2752dcd5f86b9f)

If so, than after building app, QString setTdlibParameters should be correct and we can build app.

P.S.
After resolving this, I'll add more detailed info about building.

**Comment by DylanVanAssche** [comment]
I can't explain it, I recloned the repo and added the api_secret.pri again but with capital characters and it worked!

```
APPID=123456
APP_HASH=abcdefghijklmnopqrstuvwxyz
```

**Comment by blacksailer** [comment]
Can it be closed?
