### ISSUE TITLE
can't see which message was quoted

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#43]
one annoying thing is the fact that we can't see which message was quoted if someone quote us, i don't know if this is coming with the reply feature but i thought about reporting it...

**Comment by gomerust** [comment]
It would help to see a reply like in telegram, with a a oneliner from the mentioned text. maybe with possibility to jump to the mentioned quote by clicking on it. Oftentimes its not easy to follow discussions without knowing what the people are talking about without context.

**Comment by blacksailer** [comment]
I understand that. It requires modification of MessagingModel. I'm working on it

**Comment by legacychimera247** [comment]
well this was released in latest update so i think this can be closed :)
