### ISSUE TITLE
problems with app starting and registration

### ISSUE THREAD

**Issue by carepack** [blacksailer/depecher#46]
the description and a working workaround can be found here:
https://openrepos.net/comment/24764#comment-24764

Running it now on sailfishX

**Comment by carepack** [comment]
no, it starts with a blank page and only the pulley menu is present. Then went to settings and tap logout button. After that tap the registration page appears. Starting via commandline enters the registration page immediately.
abranson tested my workaround and it fixed it for him too. I posted the workaround in the telegram channel too

**Comment by carepack** [comment]
what I haven't tested is when the line gets commented in the desktop file if the registration process gets invoked correct if you start it from app launcher

**Comment by Nokius** [comment]
workaround for now is to start via terminal `depecher` reproduced on my JollaC

**Comment by carepack** [comment]
@nokius the solution for starting from app launches is described on openrepos. cgeck the link from the first post.

**Comment by Nokius** [comment]
not reproducible with a new version for me

**Comment by blacksailer** [comment]
Can be closed? Or it is still there?
