### ISSUE TITLE
depecher not working in new 2.2.0.29

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#50]
the title says it all...in the new update (2.2.0.29) depecher only says "waiting for network" and it's not working at all...

**Comment by blacksailer** [comment]
I'll release a fix soon. 

Четверг, 31 мая 2018 г получено от legacychimera247:
> the title says it all...in the new update (2.2.0.29) depecher only says "waiting for network"
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/blacksailer/depecher/issues/5

-- 
С уважением,
Черненький Иван

**Comment by frzifus** [comment]
any updates?

**Comment by frzifus** [comment]
jep!

**Comment by paolomi** [comment]
if it is fixed, close this bug. @legacychimera247
