### ISSUE TITLE
stickers are overlapping in stickers selection

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#58]
well the title explains it all

here's a screen of it

http://jollacommunity.it/cloud/index.php/s/r7ackKoEKXJfnfi

**Comment by blacksailer** [comment]
It happens all the time? What device? What OS version?

**Comment by legacychimera247** [comment]
seems it's not happening again, anyway i have a j1 updated to lastest ea 2.0.2.29 (i think)
