### ISSUE TITLE
playback voice messages

### ISSUE THREAD

**Issue by frzifus** [blacksailer/depecher#71]
What would be a nice feature is the playback of voice messages. 
often people send voice messages and then you have to use the android app.

**Comment by paolomi** [comment]
We need an internal audio/video player to play voice messages, audio files and video files. My suggestion is to copy it from Sailorgram.

**Comment by frzifus** [comment]
[mediaplayer](https://github.com/CODeRUS/harbour-sailorgram/tree/0.9/harbour-sailorgram/qml/components/mediaplayer)
is that what you mean?

**Comment by paolomi** [comment]
Yes, it should be that, but I'm not 100% sure because I'm not a developer.

**Comment by paolomi** [comment]
@frzifus the playback of voice messages is supported now. Please verify it and close this issue.

**Comment by frzifus** [comment]
is the version already available in the open repos?

**Comment by blacksailer** [comment]
Nope, it better be here, I need to add mediaplayer to better control of audio playback

**Comment by frzifus** [comment]
I tried it. looks pretty primitive. But it works, thanks.  :+1:
