### ISSUE TITLE
use send button space for something else

### ISSUE THREAD

**Issue by legacychimera247** [blacksailer/depecher#76]
a little suggestion, the space used by the send button could be used for something else now we can send messages with the enter button, for example for the audionotes, or for having a large writing field :)

**Comment by paolomi** [comment]
Do you mean to hide "send button" only for who have set on the option "Send message by enter"?
(and show it only for who have set off that option?)

**Comment by legacychimera247** [comment]
Exactly, well anyway i already talked privately with the developer about that, this is just a reminder :)

Il Martedì 7 agosto 2018, paolomi scrive:
> Do you mean to hide "send button" only for who have set on the option "Send message by enter"?
> (and show it only for who have set off that option?)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼

-- 
Inviato dal mio Jolla
