### ISSUE TITLE
not marking chats as read

### ISSUE THREAD

**Issue by ryanrms** [blacksailer/depecher#82]
It's not marking my chat as read.  I've tried scrolling to the bottom (it wasnt already, possibly related), leaving the chat and reentering, and closing the app. Unread notification went away after a while but the chat still shows the New Message badge over the messages.

**Comment by BonoNL** [comment]
Also noticed that when a new user joins Telegram the unread mark also can't be deleted.

Maybe by chatting with the person but that is not always the desired way.
