### ISSUE TITLE
Photo selection tickbox is too small

### ISSUE THREAD

**Issue by topiasv** [blacksailer/depecher#99]
The little tick box to select images for sending is too small so a lot of mistaps happen. Either a different kind of UI solution is required or the size of the images should be increased. Also if you tap the photo and open it to full screen, it should be possible to tick it there as well. It's common to mistap and accidentally open the picture instead which results into annoying interactions where you have to go back to try and tap it again.

**Comment by blacksailer** [comment]
Replaced to select whole image since v0.5
